server:
  port: 9090

spring:
#  h2:
#    console:
#      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://java9postgres/DbMovieBlogApp
  jpa:
    hibernate:
      ddl-auto: update